services:
  flowhistory:
    build: .
    ports:
      - "9473:8000"
    environment:
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.76
      - TIME_ZONE=America/New_York
      - REQUIRE_AUTH=false
    restart: unless-stopped
