# Generated by Django 6.0.3 on 2026-04-03 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Node-RED', max_length=100)),
                ('flows_path', models.CharField(default='/nodered-data/flows.json', max_length=500)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('backup_time', models.TimeField(default='03:00')),
                ('backup_day', models.SmallIntegerField(default=0, help_text='Day of week for weekly backups (0=Monday)')),
                ('max_backups', models.PositiveIntegerField(default=20)),
                ('max_age_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('watch_enabled', models.BooleanField(default=True)),
                ('watch_debounce_seconds', models.PositiveIntegerField(default=30)),
                ('backup_credentials', models.BooleanField(default=True)),
                ('backup_settings', models.BooleanField(default=False)),
                ('restart_on_restore', models.BooleanField(default=False)),
                ('nodered_container_name', models.CharField(default='nodered', max_length=100)),
                ('last_successful_backup', models.DateTimeField(blank=True, null=True)),
                ('last_backup_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Node-RED Configuration',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('file_change', 'File Change'), ('pre_restore', 'Pre-Restore Safety')], default='manual', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('tab_summary', models.JSONField(blank=True, default=list)),
                ('changes_summary', models.JSONField(blank=True, default=dict)),
                ('includes_credentials', models.BooleanField(default=False)),
                ('includes_settings', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='backup.noderedconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
