# Generated by Django 6.0.3 on 2026-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_restore_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
