# Generated by Django 6.0.3 on 2026-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0004_backuprecord_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="noderedconfig",
            name="always_backup",
            field=models.BooleanField(default=False),
        ),
    ]
