# Generated by Django 6.0.3 on 2026-04-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_noderedconfig_always_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderedconfig',
            name='name',
        ),
        migrations.AlterField(
            model_name='noderedconfig',
            name='backup_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noderedconfig',
            name='watch_debounce_seconds',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
