# Generated by Django 6.0.3 on 2026-04-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_notify_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('file_change', 'File Change'), ('pre_restore', 'Pre-Restore Safety'), ('import', 'Import')], default='manual', max_length=20),
        ),
    ]
